#! /usr/bin/env node
'use strict';

const readline = require('readline');
const fs = require('fs');

const read = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

let output;

read.on('line', (input) => {
  console.error(input);
  console.error('args:', process.argv);
  const destination = process.argv[2];
  const payload = JSON.parse(input);
  const target = payload.source.target;
  const currentVersion = payload.version;

  // TESTING(mperrotte): listing out what's in the destination directory
  const ls = fs.readdirSync(destination, 'utf8');
  console.error('ls (destination):', ls);
  output = {
    version: currentVersion,
    metadata: [
      { name: 'target', value: target }
    ]
  };
});

read.on('close', () => {
  console.log(JSON.stringify(output));
  process.exit(0);
});
