#! /usr/bin/env node
'use strict';

const readline = require('readline');
const fs = require('fs');

const read = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

let output;

read.on('line', (input) => {
  const destination = process.argv[2];
  const payload = JSON.parse(input);
  const target = payload.source.target;
  const currentVersion = payload.version;

  output = {
    version: currentVersion,
    metadata: [
      { name: 'target', value: target }
    ]
  };
});

read.on('close', () => {
  console.log(JSON.stringify(output));
  process.exit(0);
});
